using PrintQue.Models;
using PrintQue.ViewModel;
using SQLite;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Essentials;
using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace PrintQue
{
	[XamlCompilation(XamlCompilationOptions.Compile)]
	public partial class LoginPage : ContentPage
	{
        LoginViewModel viewModel;

		public LoginPage ()
		{
			InitializeComponent ();
            RegisterLabel_Clicked();
            viewModel = new LoginViewModel();
            BindingContext = viewModel;
            viewModel.RememberMe = Preferences.Get("RememberMe", false);




        }
        protected async override void OnAppearing()
        {
            //if (_isDataLoaded)
            //    return;
            // _isDataLoaded = true;

            if (Preferences.Get("RememberMe", false))
            {
                
                viewModel.Email = await SecureStorage.GetAsync("User_Email");
                viewModel.Password = await SecureStorage.GetAsync("Password");
                if (!string.IsNullOrEmpty(viewModel.Email) && !string.IsNullOrEmpty(viewModel.Email))
                {

                    viewModel.Login();
                }
                    
            }

            base.OnAppearing();
        }

        private void RegisterLabel_Clicked()
             {
                //not an autogenerated file
                RegisterLabel.GestureRecognizers.Add(new TapGestureRecognizer()
                {
                    Command = new Command(() =>
                    {
                        
                        Navigation.PushAsync(new RegisterPage());
                        
                        
                    }
                    )
            });

        }

        private void RememberMe_Switch_Toggled(object sender, ToggledEventArgs e)
        {

        }
    }
}