using PrintQue.Models;
using PrintQue.ViewModel;
using SQLite;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace PrintQue
{
	[XamlCompilation(XamlCompilationOptions.Compile)]
	public partial class LoginPage : ContentPage
	{
        LoginViewModel viewModel;
		public LoginPage ()
		{
			InitializeComponent ();
            RegisterLabel_Clicked();
            viewModel = new LoginViewModel();
            BindingContext = viewModel;                
            

        }

        private void RegisterLabel_Clicked()
             {
                //not an autogenerated file
                RegisterLabel.GestureRecognizers.Add(new TapGestureRecognizer()
                {
                    Command = new Command(() =>
                    {
                        
                        Navigation.PushAsync(new RegisterPage());
                        
                        
                    }
                    )
            });

        }


    }
}